version: "3"
services:
  mkdocs:
    image: "${VERSION_DOCS}"
    # image: harbor-01.newtech.com.ar/newcos-teams/newcos-docs:1.0.2-dev
    deploy: 
      placement: 
        constraints: 
          - node.platform.os == linux
          - node.role == worker
    ports:
      - "8002:8000"
    # volumes:
    #   - /shared/newcos-docs:/newcos/docs
    networks:
      - dmz  

networks:
  dmz:
    external: true