version: "3"
services:
  mkdocs:
    image: harbor-01.newtech.com.ar/newcos-automation/newcos-docs:1.0.0
    deploy: 
      placement: 
        constraints: 
          - node.platform.os == linux
          - node.role == worker
    ports:
      - "8000:8000"
    volumes:
      - /shared/newcos-docs:/newcos/docs
    networks:
      - dmz  

networks:
  dmz:
    external: true