site_name: Newcos Documentation Page
theme: readthedocs
nav:
    - Docs: index.md
    - Newcos Platform:
        - Arquitectura: architecture.md
        - Infrestructura: infrastructure.md
        - Microservicios: services.md
        - Instalacion: installation.md
    - Manual de usuario:
        - Manual de configuracion: usermanual.md
        - Manual de uso: usermanual.md
repo_url: https://github.com/newtech-sm/newcos-docs
edit_uri: blob/master/newcos/docs/
dev_addr: 0.0.0.0:8000